### ISSUE TITLE
Facing issue while running prebuild binaries in alpine docker container

### ISSUE THREAD

**Issue by deekshith-elear** [alpinelinux/docker-alpine#1]
Hi,
I'm trying to run simple hello.c binary which is built in my machine and created docker image for it using alpine as base image 
### Code compilation
```
gcc hello.c -o hello
```
### DOCKER FILE
```
FROM alpine:3.4
RUN apk add --update gcc libc-dev
COPY hello /usr/bin/
```
### DOCKER CONTAINER
```
1. docker build . -t helloworld:1
2. docker run --rm -it helloworld:1
3. /bin/sh: hello: not found
```
can anyone help me out to resolve this issue

**Comment by ncopa** [comment]
You need to build it against musl libc. You cannot really copy in a binary built on MacOS, Windows or GNU/Linux and expect it to run in Alpine. Well, you can run Windows binary with `wine` and you may be able to run GNU/Linux binary if you install either `libc6-compat` or `gcompat`. It may work, even if there are no guarantee that it does.
