### ISSUE TITLE
Any way to tune configuration for time_wait issue ?

### ISSUE THREAD

**Issue by jackey** [alpinelinux/docker-alpine#10]
Many time_wait tcp connections in running docker. 

i can't set net.ipv4.tcp_tw_reuse by sysctl utils.

sysctl net.ipv4.tcp_tw_reuse 
sysctl: error: 'net.ipv4.tcp_tw_reuse' is an unknown key.

any document can help it ?

**Comment by ncopa** [comment]
This is a kernel setting and you should probably do that on the host, not in the container.
