### ISSUE TITLE
ERROR: No matching distribution found for gunicorn3

### ISSUE THREAD

**Issue by zeroshree** [alpinelinux/docker-alpine#11]
I am trying to run my Django application with alpine image. (python3 alpine image)

I need gunicorn3 to run my Django Application. 

I added following line to add gunicorn3

**RUN apk update && apk add py3-gunicorn**

but i am getting "No matching distribution found for gunicorn3" when i am running my application with following cmd

**CMD ["gunicorn3", "--bind", ":8000", "myapplication.wsgi"]**

**Comment by ncopa** [comment]
What happens if you use `alpine:3.9` docker image and do: `RUN apk add -U python3 py3-gunicorn`?

**Comment by zeroshree** [comment]
it is installing successfully but with gunicorn3 it is not able to run my django application.  May I  close this issue ? I resolved with ubuntu image since my application suits ubuntu image.
