### ISSUE TITLE
apk errors with latest (minirootfs-20200917) 32bit arm images

### ISSUE THREAD

**Issue by minusdelta** [alpinelinux/docker-alpine#110]
armv7:
```
docker run --rm -it alpine@sha256:9dcd267f53cb0afee197077bb1c8e2ec7f01d5340c33f7eb6c6ee1031813e721 \
apk add -vv --no-cache curl

fetch https://dl-cdn.alpinelinux.org/alpine/edge/main/armv7/APKINDEX.tar.gz
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/edge/main/armv7/APKINDEX.tar.gz: temporary error (try again later)
fetch https://dl-cdn.alpinelinux.org/alpine/edge/community/armv7/APKINDEX.tar.gz
3070120864:error:0D0D90AD:asn1 encoding routines:ASN1_TIME_adj:error getting time:crypto/asn1/a_time.c:330:
3070120864:error:0D0D90AD:asn1 encoding routines:ASN1_TIME_adj:error getting time:crypto/asn1/a_time.c:330:
3070120864:error:0D0D90AD:asn1 encoding routines:ASN1_TIME_adj:error getting time:crypto/asn1/a_time.c:330:
3070120864:error:0D0D90AD:asn1 encoding routines:ASN1_TIME_adj:error getting time:crypto/asn1/a_time.c:330:
3070120864:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1913:
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/edge/community/armv7/APKINDEX.tar.gz: Permission denied
ERROR: unsatisfiable constraints:
  curl (missing):
    required by: world[curl]
```

Same for armv6/armhf:
```
docker run --rm -it alpine@sha256:b0729a3bebc8b269c81293eb8eb261db69f0f16d59439ababf13165dff1b4881 \
apk add -vv --no-cache curl

fetch https://dl-cdn.alpinelinux.org/alpine/edge/main/armhf/APKINDEX.tar.gz
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/edge/main/armhf/APKINDEX.tar.gz: temporary error (try again later)
fetch https://dl-cdn.alpinelinux.org/alpine/edge/community/armhf/APKINDEX.tar.gz
3070026656:error:0D0D90AD:asn1 encoding routines:ASN1_TIME_adj:error getting time:crypto/asn1/a_time.c:330:

[snip]
```
... I had to run it twice to get an error message.

**Comment by tianon** [comment]
This sounds suspiciously similar to https://github.com/moby/moby/issues/40734 -- did the libc update in the latest edge release update to use the new 64bit time-related syscalls?

(If so, it'll probably be "fixed" if you update `libseccomp2` on your host to 2.4.2 or higher, and make sure your version of Docker is 19.03.11 or higher.)

**Comment by minusdelta** [comment]
On the node in question (`Debian 9`) updating `libseccomp2` isnt possible.
But for testing I found another `armv7` node running `Ubuntu  18.04.5 LTS` in the cluster.
With `libseccomp2 2.4.1`: fail, with `libseccomp2 2.4.3`: success.

@tianon thanks for this hint, very much appreciated!

**Comment by Lukas1818** [comment]
I have the same issues with the alpine:edge docker image on my Raspberry Pi 2 (armv7).

Does someone known a workaround?

**Comment by tianon** [comment]
> My host (Debian) has only libseccomp2 2.3.3.

For Debian, you'll likely have to enable `buster-backports` in your `sources.list` to get a new enough version.  For Raspbian, you'll likely have to get the newer version from `bullseye` (because I don't think Raspbian supports/rebuilds `buster-backports`).

**Comment by may00r** [comment]
> I have the same issue with the alpine:edge docker image on my Raspberry Pi 2 (armv7).
> 
> Does someone known a workaround? My host (Debian) has only libseccomp2 2.3.3.

I downloaded deb package and installed manually.

**Comment by Lukas1818** [comment]
Replacing the package manually is may not a god idea. Other package which link again libseccomp2 could break.
Raspbian does not support backports, so this is not a option.
I think I will switch my host OS to alpine. I have already planned this, but not done it yet.

**Comment by Wuodan** [comment]
> > My host (Debian) has only libseccomp2 2.3.3.
> 
> For Debian, you'll likely have to enable `buster-backports` in your `sources.list` to get a new enough version. For Raspbian, you'll likely have to get the newer version from `bullseye` (because I don't think Raspbian supports/rebuilds `buster-backports`).

It seems supported, see here [https://gitea.thebrokenrail.com/TheBrokenRail/minecraft-pi-reborn](https://gitea.thebrokenrail.com/TheBrokenRail/minecraft-pi-reborn)

**Comment by ncopa** [comment]
I suppose there is nothing we can fix in the alpine image, so I close this issue.

**Comment by Lukas1818** [comment]
> > > My host (Debian) has only libseccomp2 2.3.3.
> > 
> > 
> > For Debian, you'll likely have to enable `buster-backports` in your `sources.list` to get a new enough version. For Raspbian, you'll likely have to get the newer version from `bullseye` (because I don't think Raspbian supports/rebuilds `buster-backports`).
> 
> It seems supported, see here https://gitea.thebrokenrail.com/TheBrokenRail/minecraft-pi-reborn

They use the backports from Debian. I do not think using repository from another distribution is a good idea, even if they are similar.

**Comment by mulat666** [comment]
I have similar problem with my RPi , manual installation of https://debian.pkgs.org/sid/debian-main-armhf/libseccomp2_2.5.1-1_armhf.deb.html solved issue.
