### ISSUE TITLE
alpine doesnt work with no-new-privileges set

### ISSUE THREAD

**Issue by najtin** [alpinelinux/docker-alpine#126]
```bash
$ docker run -it --rm --security-opt=no-new-privileges:true alpine sh
standard_init_linux.go:211: exec user process caused "operation not permitted"
```
runc is on version 1.0.0~rc10, so the start fails at https://github.com/opencontainers/runc/blob/v1.0.0-rc10/libcontainer/standard_init_linux.go#L211
```go
	if err := syscall.Exec(name, l.config.Args[0:], os.Environ()); err != nil {
		return newSystemErrorWithCause(err, "exec user process")
	}
```
I don't know the arguments in the syscall.Exec, but i think it is related to the image, in this case alpine.

**Comment by najtin** [comment]
This seems to be related https://github.com/coreos/bugs/issues/1796
as per https://github.com/coreos/bugs/issues/1796#issuecomment-326130039 the command was seemingly working at some point in time

**Comment by ncopa** [comment]
I am not able to reproduce.
```
$ docker run -it --rm --security-opt=no-new-privileges:true alpine sh
/ # 
```
What is the host OS? do you have selinux or apparmor enabled?

I can not see how this is something we can fix in the alpine image?

**Comment by najtin** [comment]
Hm, thanks! 
Host is Ubuntu 20.04.1 LTS
SELinux is not installed on the host.
AppArmor is enforced on dockerd:
/snap/docker/471/bin/dockerd (1324) snap.docker.dockerd
as you can see, docker is installed via snap
The AppArmor profile is the default profile (or at least i did not touch it manually).

**Comment by tianon** [comment]
I can reproduce (Docker via snap is really not A Good Time - it's containers inside containers).

However, looking in the `dmesg` logs, I see:

```
[  714.884943] audit: type=1400 audit(1608142125.849:53): apparmor="DENIED" operation="exec" info="no new privs" error=-1 profile="snap.docker.dockerd" name="/bin/sh" pid=2874 comm="runc:[2:INIT]" requested_mask="x" denied_mask="x" fsuid=0 ouid=0 target="docker-default"
```

So I think this is actually a bug in `snapd`'s confinement of Docker, and https://github.com/snapcore/snapd is likely the appropriate place to report this (I think you'll find that it's reproducible with any image, not just Alpine).

**Comment by najtin** [comment]
@tianon Yes, `--security-opt=no-new-privileges:true` does not work with any image on snap docker. Then, sorry again that i bothered you with that. I will take it over to snapd and install docker via apt in the future. :) thanks again
