### ISSUE TITLE
Build for 3.12.6 without amd64

### ISSUE THREAD

**Issue by brotbert** [alpinelinux/docker-alpine#167]
I don't see any image in [latest 3.12.6 build](https://hub.docker.com/layers/alpine/library/alpine/3.12.6/images/sha256-692283d5d175df2a57fb2ed4e987fb08e465fd36544aa4843190f7b8037c888e?context=explore) for _amd64_.

Can someone please confirm this?

Seems this was regression was introduced in the update on 3.12.6 (87a91a7).

**Comment by tianon** [comment]
Are you sure?  The 3.12.6 tag appears to include `amd64` in my testing:

```console
$ docker run --rm mplatform/mquery alpine:3.12.6
Image: alpine:3.12.6 (digest: sha256:834e9309b5ef0f78d8d20ef0652e7b0272fe97b5baf45720e1b830eaf013cc1b)
 * Manifest List: Yes (Image type: application/vnd.docker.distribution.manifest.list.v2+json)
 * Supported platforms:
   - linux/amd64
   - linux/arm/v6
   - linux/arm/v7
   - linux/arm64/v8
   - linux/386
   - linux/ppc64le
   - linux/s390x

```

**Comment by brotbert** [comment]
Hi @tianon,

thanks! You're right.

Honestly I haven't re-tried this and assumed that it'd also not work like last week:

```
$ docker image pull alpine:3.12.6
3.12.6: Pulling from library/alpine
no matching manifest for linux/amd64 in the manifest list entries
```

Now it works like a charm.

And for the Docker Hub UI, it looks like my browser had still a cached fragment of [images](https://hub.docker.com/v2/repositories/library/alpine/tags/3.12.6/images) without _amd64_.

Thanks for your quick help!
