### ISSUE TITLE
Question: Repo and Build Process for Minirootfs

### ISSUE THREAD

**Issue by brompwnie** [alpinelinux/docker-alpine#183]
Hello,

Please redirect me to the appropriate forum if this is not the correct place but I am trying to locate the repo and build process for the mini-root-fs tar's used in the alpine image. For example, https://dl-cdn.alpinelinux.org/alpine/v3.14/releases/x86_64/alpine-minirootfs-3.14.0-x86_64.tar.gz

**Comment by TBK** [comment]
https://gitlab.alpinelinux.org/alpine/aports/-/tree/master/scripts -> mkimg.minirootfs.sh

**Comment by brompwnie** [comment]
Thank you.
