### ISSUE TITLE
Question: /bin/busybox and /lib/*.so source and build scripts

### ISSUE THREAD

**Issue by brompwnie** [alpinelinux/docker-alpine#186]
Hello,

I am trying to determine where and how the Busybox binary is compiled, is there a repo with this information? Additionally, I'm looking to find the same for the share objects that are located in "/lib/*". 

Thanks,

**Comment by ncopa** [comment]
build script for busybox: https://gitlab.alpinelinux.org/alpine/aports/-/blob/3.14-stable/main/busybox/APKBUILD

You find the build scripts for the other packages there as well.

The script to generate  minirootfs tarball which is used as the base for docker-alpine is here: https://gitlab.alpinelinux.org/alpine/aports/-/blob/3.14-stable/scripts/mkimg.minirootfs.sh
