### ISSUE TITLE
bug: https://hub.docker.com/r/arm32v6/alpine/

### ISSUE THREAD

**Issue by userdocs** [alpinelinux/docker-alpine#194]
Since this update i am seeing this error in github actions

```
Run docker run --name multiarch -it -d -w /root -e CXXFLAGS="--static -static -std=c++17" -e CPPFLAGS="--static -static" -e LDFLAGS="--static -static" --platform linux/arm/v6 -v /home/runner/work/iperf3-static/iperf3-static:/root arm32v6/alpine:edge
Unable to find image 'arm32v6/alpine:edge' locally
edge: Pulling from arm32v6/alpine
0d0f9d41af7f: Pulling fs layer
0d0f9d41af7f: Verifying Checksum
0d0f9d41af7f: Download complete
0d0f9d41af7f: Pull complete
Digest: sha256:709fcd97960580940702a579436f29ecf079d04bfd546af98a8bb9fe236f0e46
Status: Downloaded newer image for arm32v6/alpine:edge
docker: Error response from daemon: image with reference arm32v6/alpine:edge was found but does not match the specified platform: wanted linux/arm/v6, actual: linux/arm/v7.
See 'docker run --help'.
Error: Process completed with exit code 125.
```

It would seem this is incorrect `linux/arm/v7` if i am still using `arm32v6/alpine:edge` as the container?

**Comment by tianon** [comment]
This is an unfortunate intersection of a few factors (Docker 20.10+, containerd's platform normalization, `docker build`'s default behavior), but I've filed https://github.com/docker-library/bashbrew/issues/29 to track this issue in `bashbrew` because that's probably going to be the most appropriate place to fix the specific case of the metadata on these Alpine images.

**Comment by userdocs** [comment]
Ok, thanks for the update. My [workflow](https://github.com/userdocs/iperf3-static/actions/workflows/multiarch_qemu_iperf3.yml) just started failing and I did not fully understand why so this is helpful info to know. I'll keep an eye on it and hopefully it is resolved .

**Comment by userdocs** [comment]
I still have this with the latest released image (16 hours ago) https://hub.docker.com/r/arm32v6/alpine/

https://github.com/userdocs/iperf3-static/runs/3449942070?check_suite_focus=true

Any idea when the fix will filter through?

**Comment by tianon** [comment]
I'm not sure why Docker Hub doesn't show it, but the pushed image definitely has `variant: "v6"` set: :confused:

- https://explore.ggcr.dev/?image=arm32v6/alpine:latest
- https://explore.ggcr.dev/json/index.docker.io/arm32v6/alpine@sha256:651b237e41d5a4f13081d1def5aee149bfe130e33cc4834bca7c8554b7f4a21a?mt=application/vnd.docker.container.image.v1+json

```json
{
...
"architecture": "arm",
...
"os": "linux",
...
"variant": "v6"
}
```

**Comment by userdocs** [comment]
I see this also when using doccker rootless on a server

```bash
docker run --rm arm32v6/alpine:edge sh -c 'cat /etc/*release'
```

```bash
WARNING: The requested image's platform (linux/arm/v7) does not match the detected host platform (linux/amd64) and no specific platform was requested
3.15.0_alpha20210804
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.15.0_alpha20210804
PRETTY_NAME="Alpine Linux edge"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"

**Comment by userdocs** [comment]
Looking here at the hash i see this is maybe a month old?

https://hub.docker.com/layers/arm32v6/alpine/edge/images/sha256-1e11ccd5ee517815f685f795a82e9b02274657bd5c0c103370cdd3cdedef5b15?context=explore

**Comment by tianon** [comment]
Yeah, somehow `arm32v6/alpine:edge` didn't get updated properly and had `variant: "v7"` of all things -- it should be updated now though (I've just forced it to rebuild).

**Comment by userdocs** [comment]
Yes that was it. It is working now https://github.com/userdocs/iperf3-static/runs/3465215662?check_suite_focus=true

Thanks for the fix.
