### ISSUE TITLE
Image needs apk-tools 2.12.6-r0

### ISSUE THREAD

**Issue by santoshjpawar** [alpinelinux/docker-alpine#195]
The security scan that we use for scanning the images is complaining for the apk-tools version **2.12.5** in docker.io/alpine:3 image.

We use opm tool (part of Operator SDK https://github.com/operator-framework/operator-sdk) to build the bundle image and add it to the catalog image using below command.
`opm index add  --bundles ${env.DOCKER_REGISTRY}/${env.IMG_PATH_PREFIX?:""}${bundleName}@\${digest}`

The opm tool uses the **upstream-builder.Dockerfile** while building the catalog image. This Dockerfile uses **alpine:3** as the base image.
https://github.com/operator-framework/operator-registry/blob/master/upstream-builder.Dockerfile#L12

The latest alpine:3 image has **apk-tools-2.12.5-r1**.

It can be updated by running `apk update && apk upgrade` command when catalog image is running. However, we are building the catalog image using opm command and do not have any control over running the commands in the Dockerfile while building it. So when the catalog image is scanned by the vulnerability scan, it is complaining for the apk-tools version **2.12.5**.

Can you please provide any timelines by which the alpine:3 image will be rebuilt to have latest apk-tools version **2.12.6-r0** or higher?

**Comment by realHorst** [comment]
Just letting you know that as of alpine:3.14.1 the image contains apk-tools-2.12.7-r0.

**Comment by mthalman** [comment]
Why hasn't alpine:3.13 been updated to reference 2.12.7-r0 instead of 2.12.5-r0?

**Comment by ncopa** [comment]
https://www.alpinelinux.org/posts/Alpine-3.11.12-3.12.8.-3.13.6-released.html
