### ISSUE TITLE
Why not just provide a tag like :3 on Docker Hub

### ISSUE THREAD

**Issue by ahmetb** [alpinelinux/docker-alpine#21]
https://hub.docker.com/_/alpine only offers tags:
```
20190508, edge
3.9.4, 3.9, latest
3.8.4, 3.8
3.7.3, 3.7
3.6.5, 3.6
```

I don't want to use `alpine:latest`, assuming we all can tell what's wrong with that.

The only other options I have are:

- pick something like `3.9`: it'll be deleted in a couple of years later and my builds will start breaking.
- subscribe to updates of alpine releases (like 3.10): I don't think I have time to track these.

Many other official images provide convenience alias tags with their semver major versions, like `golang:1` or `python:3`. I think `alpine` should follow suit, unless there's a good reason to not to.

**Comment by ncopa** [comment]
This will effectively be the same as `latest`, at least til 4.0 is out.

I guess it won't hurt to add another tag for `3`.

**Comment by ncopa** [comment]
fixed with https://github.com/docker-library/official-images/commit/612267702ed5e2f99c685f9a907d92b53e69c1fe

**Comment by ahmetb** [comment]
You’re the best. Thanks.
