### ISSUE TITLE
www-data group is included in latest alpine 3.14

### ISSUE THREAD

**Issue by Mrono** [alpinelinux/docker-alpine#211]
Why is this suddenly a thing?  I use the www-data group group my dockerfiles as it has not been there and now with this change I have to fix all my images. This did not used to be a thing even on 3.14 and I'd like to know why.

**Comment by HRio** [comment]
Yes it was added in v3.14.0_rc3 with this commit:
https://github.com/alpinelinux/aports/commit/b881d448f7906ee654d95cbd75c3d1b723b65b4f

see the commit message for more info on why it was added.
