### ISSUE TITLE
alpine:3.14.x error building image

### ISSUE THREAD

**Issue by jackton1** [alpinelinux/docker-alpine#233]
See: https://github.com/tj-actions/changed-files/runs/5192954701?check_suite_focus=true

![Screen Shot 2022-02-14 at 8 02 50 PM](https://user-images.githubusercontent.com/17484350/153972781-22987b1a-b66d-4901-b450-45db729cfe1b.png)

**Comment by jackton1** [comment]
https://github.com/gliderlabs/docker-alpine/issues/386

**Comment by taspeotis** [comment]
It seems that https://dl-cdn.alpinelinux.org is down:

> **Error 503 Backend is unhealthy**
> Backend is unhealthy

The status page is not helpful.

![image](https://user-images.githubusercontent.com/1189399/153976536-302ca307-ef80-4f4e-9311-7429c22d691d.png)

**Comment by hiroshi** [comment]
For a workaround use a mirror or two.
e.g.
`apk add -X https://mirrors.gigenet.com/alpinelinux/v3.14/main openssh git`

**Comment by pianist5555** [comment]
I have same problem now.

**Comment by taspeotis** [comment]
I have just been able to download [dl-cdn.alpinelinux.org/alpine/v3.14/main/x86_64/APKINDEX.tar.gz](https://dl-cdn.alpinelinux.org/alpine/v3.14/main/x86_64/APKINDEX.tar.gz) so I assume it's fixed.

**Comment by ncopa** [comment]
We got DDOSed. Should be back again now.
