### ISSUE TITLE
alpine:3.15 error building images

### ISSUE THREAD

**Issue by tuc0w** [alpinelinux/docker-alpine#236]
![image](https://user-images.githubusercontent.com/843830/155134153-f97e0935-98fa-457c-822f-6c456f30021b.png)

Are the repositories down again like a few days ago?

> We got DDOSed. Should be back again now.
_Originally posted by @ncopa in https://github.com/alpinelinux/docker-alpine/issues/233#issuecomment-1039802379_

**Comment by ncopa** [comment]
Should be good now.
```
$ docker run --rm -it alpine:3.15 apk update
fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/community/x86_64/APKINDEX.tar.gz
v3.15.1-2-g91c7a9f3aa [https://dl-cdn.alpinelinux.org/alpine/v3.15/main]
v3.15.1-3-g5a0989e449 [https://dl-cdn.alpinelinux.org/alpine/v3.15/community]
OK: 15860 distinct packages available
```
