### ISSUE TITLE
Curl and wget is failing consistently with Alpine 3.15 

### ISSUE THREAD

**Issue by vkode333** [alpinelinux/docker-alpine#238]
I am using node:16-alpine and node:16.14-alpine versions of docker images. Both images built with alpine 3.15 os. With these docker images https calls over any DNS failing with  curl and wget. “Unable to resolve hostname” error is intermittently throwing. To make it work during docker build I added my host name and  it’s resolving IP to make it work. Does any know why this inconsistency with connection errors alpinelinux  3.15 version.

**Comment by selfcommentingcode** [comment]
@vkode333 I am suddenly facing the same issue. It looks like you got it working. Can share exactly what you did to fix this? A screenshot or something will really benefit me; I'm relatively new at this. Thank you.

**Comment by westwind-sc** [comment]
Could you share the reproduced steps and the docker info?

**Comment by ncopa** [comment]
Sounds like something is bad in your network/dns setup.

**Comment by ncopa** [comment]
I cannot reproduce the issue and it works for me.
```
$ docker run --rm -it node:16.14-alpine sh -c "apk add -q -U curl
 && curl https://alpinelinux.org > /dev/null && echo 'all good!'"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8541  100  8541    0     0  89767      0 --:--:-- --:--:-- --:--:-- 89905
all good!
```
There is nothing we can do without more details.

That said, please make sure that you don't use a buggy version of docker and libseccomp. See https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.14.0#faccessat2
