### ISSUE TITLE
openjdk8 links are wrong

### ISSUE THREAD

**Issue by onlyhuman** [alpinelinux/docker-alpine#241]
After a fresh pull of the latest image I've tried to install openjdk8, but the links are incorrectly set up in /usr/bin folder pointing to the /usr/lib/jvm/default-jvm/jre/bin folder. 
The error I got:
```
/ # pwd
/
/ # javac
/bin/sh: javac: not found
```
Caused by:
```
/ # ls -l /usr/bin/jav*
lrwxrwxrwx    1 root     root            35 Mar 11 09:52 /usr/bin/java -> ../lib/jvm/default-jvm/jre/bin/java
lrwxrwxrwx    1 root     root            36 Mar 11 09:52 /usr/bin/javac -> ../lib/jvm/default-jvm/jre/bin/javac
lrwxrwxrwx    1 root     root            38 Mar 11 09:52 /usr/bin/javadoc -> ../lib/jvm/default-jvm/jre/bin/javadoc
lrwxrwxrwx    1 root     root            36 Mar 11 09:52 /usr/bin/javap -> ../lib/jvm/default-jvm/jre/bin/javap
```
The correct one is  /usr/lib/jvm/default-jvm/bin
A workaround could be to add the correct path to the $PATH variable.

**Comment by ncopa** [comment]
should be fixed with alpinelinux/aports@5a0989e44934a86048b18b4253ec220cbd07f90f
