### ISSUE TITLE
OpenSSL and zlib vulnerabilities in alpine 3.15 docker image

### ISSUE THREAD

**Issue by mshah-aiondigital** [alpinelinux/docker-alpine#256]
The docker image available on dockerhub for alpine 3.15 is 2 months old. Vulnerabilities have been reported (and fixed) against OpenSSL and zlib as can be seen [here](https://pkgs.alpinelinux.org/packages?name=openssl*&branch=v3.15) and [here](https://pkgs.alpinelinux.org/packages?name=zlib*&branch=v3.15). However, the latest docker image tagged `alpine:3.15` is still not updated. Can this be updated?

**Comment by psy0rz** [comment]
latest seems to point to 3.16 now?

**Comment by mshah-aiondigital** [comment]
Yes, we can close this now.
