### ISSUE TITLE
Support pipefail with POSIX:2022

### ISSUE THREAD

**Issue by tgross35** [alpinelinux/docker-alpine#258]
Hello all,

As I understand, POSIX:2022 will include the option to `set -o pipefail`. As Alpine uses some form of the POSIX-compliant `sh`, would it be possible to add this option in one of the upcoming releases?

**Comment by ncopa** [comment]
Do you have any reference for this?

Adding support for `pipefail` sounds like a great thing, and I would like to create a feature request for upstream busybox.

**Comment by tgross35** [comment]
@ncopa glad you're on board! Didn't realize that sh came from busybox.

Finding references is tough, this is the best I can do: https://www.austingroupbugs.net/view.php?id=789. The POSIX docs are pretty locked down it seems, so I'm relying on some word of mouth (and that thread is pretty convincing). Even if the POSIX spec doesn't come out until 2023, I definitely don't think it's a bad thing to add before then.

Is the busybox request something you'll do, or that you'd like me to do? (I just don't know where since it looks like only the mirror is on GH)

**Comment by ncopa** [comment]
Would be great if you could help me with a busybox request. You can do so by creating an issue here: https://bugs.busybox.net/ and I would also recommend that you write an email to the [busybox mailing list](http://lists.busybox.net/mailman/listinfo/busybox).

The maintainers are generally slow on responding but the sooner this gets attention the better. I might even have a look at implementing this myself and send them a patch if I get the time.

**Comment by tgross35** [comment]
Sounds good, I will do so later today and let you know. Thanks for the info!

**Comment by tgross35** [comment]
OK cool, bugz is here https://bugs.busybox.net/show_bug.cgi?id=14851, and I got your email from a patch and CC'd you on what I sent to the mailing list

**Comment by tgross35** [comment]
Hey, that's a good point - easy fix. Thanks Natanael
