### ISSUE TITLE
how to change the dns server in /etc/resolv.conf

### ISSUE THREAD

**Issue by felixx** [alpinelinux/docker-alpine#27]
it says the file is generated by `systemd-resolved`, but I cannot find it, how to overwrite the default dns setting? if I edit the /etc/resolve.conf and commit the changes, the changes will be overwriten to the default value after the container restarted, thanks.

**Comment by 4ops** [comment]
> it says the file is generated by `systemd-resolved`, but I cannot find it, how to overwrite the default dns setting? if I edit the /etc/resolve.conf and commit the changes, the changes will be overwriten to the default value after the container restarted, thanks.

```shell
$ sudo systemctl disable systemd-resolved && sudo systemctl stop systemd-resolved
$ sudo unlink /etc/resolv.conf
$ echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf
$ sudo systemctl daemon-reload && sudo systemctl restart docker
```
