### ISSUE TITLE
How to configure the maximum number of threads for a specified user. For example, in centos, it is configured through the /etc/security/limits.d/20-nproc.conf file, but I did not find an alpine related configuration file.

### ISSUE THREAD

**Issue by luomengY** [alpinelinux/docker-alpine#277]
How to configure the maximum number of threads for a specified user. For example, in centos, it is configured through the /etc/security/limits.d/20-nproc.conf file, but I did not find an alpine related configuration file.

**Comment by ncopa** [comment]
Please see:
https://gitlab.alpinelinux.org/alpine/aports/-/issues/14141

https://gitlab.alpinelinux.org/alpine/aports/-/issues/11945
