### ISSUE TITLE
alpine repo has a hacked image?

### ISSUE THREAD

**Issue by jamesloh** [alpinelinux/docker-alpine#29]
Hi, my machine keeps pulling down an image from the alpine repo that just pings 8.8.8.8 non-stop.

alpine              <none>              4d90542f0623        3 weeks ago         5.58MB

A container is started from it which is always called happy_wu.something
66d91cdce98b        alpine:latest       "ping 8.8.8.8"      About a minute ago   Up About a minute                       happy_wu.1.srxl75sc4s4m6jewkb7cr6tnn

After I rm -f the container, it returns again. Is it possible to pull the image from another repo and then make it look like it came from alpine? 

How do I find out what is triggering this 'docker run --name happy_wu.something'?

I have stopped docker service. Does anyone know how to find out what is triggering this image to run as happy_wu.something?

**Comment by ncopa** [comment]
Sorry, but alpine docker image has no possibility to start or stop other docker images. This is not something we can fix for you.
