### ISSUE TITLE
where could get image for loogson(mips64)?

### ISSUE THREAD

**Issue by lovebaby979** [alpinelinux/docker-alpine#30]
where could get image for loogson(mips64)?
I want to build image run on loogson linux,but I couldn't find the release for loogson(mips64) linux.

**Comment by ncopa** [comment]
We have not ported alpine to mips64 (yet), so there exist no image for it.

**Comment by xidiandb** [comment]
why?

**Comment by ncopa** [comment]
Because we are kinda busy supporting the 7 other architectures.
