### ISSUE TITLE
alpine 3.17.2 missing linux/amd64

### ISSUE THREAD

**Issue by cicirello** [alpinelinux/docker-alpine#303]
## Summary
Alpine 3.17.2 appears to be missing the linux/amd64 architecture.

## Details

When attempting to pull, result is following error:

```
Step 1/3 : FROM alpine:3.17.2
no matching manifest for linux/amd64 in the manifest list entries
3.17.2: Pulling from library/alpine
Error: Process completed with exit code 1.
```

The tag page (https://hub.docker.com/_/alpine/tags) shows all other architectures available for `3.17.2` except for linux/amd64. Additionally, the `latest` and `3.17` tags list the linux/amd64 architecture with the SHA for `3.17.1`.

**Comment by james-d-elliott** [comment]
Tricked again by doijanky! That little prankster.

**Comment by cicirello** [comment]
It looks like this has been fixed, so I'm closing the issue.
