### ISSUE TITLE
Are the alpine container images compliant with FIPS?

### ISSUE THREAD

**Issue by aramsamy** [alpinelinux/docker-alpine#310]
Are the alpine container images compliant with FIPS? If not, when can we expect them to become a part of the image?

**Comment by aramsamy** [comment]
Any update on this issue ?

**Comment by ncopa** [comment]
No, alpine is not FIPS certified and it is uncertain if it will ever be. Someone needs to sponsor the work to:

- investigate what needs to be done to see if it possible at all
- do the actual work (special buidl will be required likely)
- pay for the FIPS certificate (if needed)

Please reach out to me in private if there are anyone willing to sponsor this.
