### ISSUE TITLE
Add arm32v8 image?

### ISSUE THREAD

**Issue by tmm1** [alpinelinux/docker-alpine#32]
Hi, thanks for maintaining these wonderful base images.

I am using arm32v7 and arm64v8 images, but I also have some devices running armv8l.

Can you point me to the build scripts used to generate and upload base images? I would be happy to help contribute some patches which add arm32v8 support.

**Comment by tmm1** [comment]
I see the list is here:

https://github.com/alpinelinux/docker-alpine/blob/b84e5f8fada800a2f19e727d30e2e85302de218c/fetch-latest-releases.lua#L84

So the issue is that alpine itself does not publish armv8 minirootfs yet.

**Comment by ncopa** [comment]
> So the issue is that alpine itself does not publish armv8 minirootfs yet.

Correct. We have no current plans to port to arm32v8 as it require significant amount of work, not only to do the initial porting, but also to keep it maintained for years.
