### ISSUE TITLE
Running executable file returns failed to find the file error

### ISSUE THREAD

**Issue by athulj07** [alpinelinux/docker-alpine#322]
We are using the base version of alpine linux but we are facing this error mesages while running certain C++ libraries

issues; Error relocating /opt/tools/run_tools: _ZNSt7__cxx118numpunctIcE22_M_initialize_numpunctEP15__locale_struct: symbol not found
            Error relocating /opt/tools/run_tools: malloc_info: symbol not found

**Comment by athulj07** [comment]
cc @onlykumarabhishek

**Comment by ncopa** [comment]
> Error relocating /opt/tools/run_tools: _ZNSt7__cxx118numpunctIcE22_M_initialize_numpunctEP15__locale_struct: symbol not found

You are lacking a library that provides `_ZNSt7__cxx118numpunctIcE22_M_initialize_numpunctEP15__locale_struct`. probably libstdc++?

> Error relocating /opt/tools/run_tools: malloc_info: symbol not found

looks like you are trying to run binaries compiled for other system. If its a mac binary, run it on a Mac. If its a GNU libc minary, run it on a GNU libc system.

You might be able to use `gcompat` package, but I would really recommend either rebuild the application against mus libc or run it on the platform it was built for.
