### ISSUE TITLE
Truncated UDP DNS responses not retried over TCP

### ISSUE THREAD

**Issue by matulek** [alpinelinux/docker-alpine#326]
When a DNS response gets truncated over UDP because of the length, alpine seems to not retry the query using TCP.

Reproducible example:

`docker run -ti --rm --entrypoint nslookup alpine:3.18 -type=txt test2137.raws.app`

result:

```
Server:		192.168.0.1
Address:	192.168.0.1:53

Non-authoritative answer:

```
(answer empty)

And on the host (Fedora 34) it looks like this:

```
nslookup -type=txt test2137.raws.app
;; Truncated, retrying in TCP mode.
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
test2137.raws.app	text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ut ex facilisis massa varius vehicula. Duis cursus dictum dui ut sagittis. Nulla imperdiet sapien faucibus pellentesque gravida. Donec non ultricies libero. Aliquam finibus turpis eros, vitae " "lacinia nunc gravida eu. Maecenas vel volutpat neque. Maecenas ornare, risus sed tincidunt tempor, arcu diam tincidunt nunc, vitae efficitur ante ipsum a mi. Praesent cursus elit justo, non accumsan felis posuere sit amet. Nulla vel metus ipsum. Sed et to" "rtor sit amet nulla ullamcorper porttitor. Donec laoreet posuere turpis sed commodo. Nam feugiat erat ac orci lacinia, ullamcorper rutrum augue tempor. Cras pellentesque, lorem at venenatis sodales, eros orci rhoncus mauris, vel porta tellus felis vestibu" "lum neque. Vivamus in lacus lectus. Curabitur sed semper risus, vel ultricies orci. Quisque vestibulum mauris id augue mollis, sed auctor dui accumsan.Suspendisse sit amet enim vehicula, suscipit enim at, lobortis diam. Vestibulum congue, risus sit amet n" "unc."

Authoritative answers can be found from:
```

This is not only the nslookup issue, I've encountered this problem when my application was trying to resolve `email-smtp.eu-central-1.amazonaws.com` domain records in PHP (`php:7-fpm-alpine` image).

It seems to be related to the #152 .

**Comment by ncopa** [comment]
I think busybox nslookup uses its own resolver and not libc.

```c
//config:config FEATURE_NSLOOKUP_BIG
//config:   bool "Use internal resolver code instead of libc"
```

```console
ncopa-desktop:~/aports/main/busybox (master)$ grep NSLOOKUP_BIG busyboxconfig
CONFIG_FEATURE_NSLOOKUP_BIG=y
```

https://gitlab.alpinelinux.org/alpine/tsc/-/issues/43 is about musl libc and not busybox.

**Comment by ncopa** [comment]
> This is not only the nslookup issue, I've encountered this problem when my application was trying to resolve email-smtp.eu-central-1.amazonaws.com domain records in PHP (php:7-fpm-alpine image).
>
> It seems to be related to the #152 .

#152 mentions alpine 3.13, which does not have TCP fallback.

But ping is actually able to reolve the `email-smtp.eu-central-1.amazonaws.com`:

```console
$ docker run --rm -it alpine:3.18 ping email-smtp.eu-central-1.amazonaws.com
PING email-smtp.eu-central-1.amazonaws.com (52.57.120.116): 56 data bytes
```

But it is also able to do so with 3.13:
```console
$ docker run --rm -it alpine:3.13 ping email-smtp.eu-central-1.amazonaws.com
PING email-smtp.eu-central-1.amazonaws.com (52.57.120.116): 56 data bytes
```

Also, the `php:7-fpm-alpine` is based on alpine 3,16 and not the "fixed" 3.18:
```console
$ docker run --rm -it php:7-fpm-alpine cat /etc/alpine-release
3.16.3
```

You also don't mention exactly what your application is trying to resolve or how? A records? TXT records?

**Comment by matulek** [comment]
I'm sorry, I had really rough day yesterday and I didn't even have time to finish my answer.

As I said, it seemed to be a temporary change in DNS record of the mentioned Amazon domain. I know that it was the case, because during the malfunction of my application I've checked the resolution of this domain using `nslookup` and at that time it reported a TCP fallback warning for it (not inside the Alpine container of course, it was empty there).

> You also don't mention exactly what your application is trying to resolve or how? A records? TXT records?

My application is not resolving TXT records, the record I've used in this issue report is just for testing purposes. It was easier to create a long record using TXT. I don't know if it matters, I assume the issue here is the record length and not the type.

> I think busybox nslookup uses its own resolver and not libc.

I'm not sure if I understand, so the `nslookup` in the Alpine doesn't use the standard system resolver? Then why it's changing behavior after installing `bind-tools`, is this package overwriting the `nslookup` tool or is it something else? I might try a different way of analysis.

**Comment by matulek** [comment]
As of this Amazon domain case, it seems odd that it was resolved only over the TCP, I can't quite manage to create my own A record that long (and currently I've created one with 10 IP addresses). There could be some weird DNS caching issue on my Kubernetes cluster. Either way, it was resolvable, just not inside the Alpine container due to the DNS bug. I'd really like to replicate this problem to check if on 3.18 version it's still misbehaving without using the `nslookup` or any platform-specific resolver (f. ex. NodeJS DNS implementation resolves this long TXT record of mine on all Alpine versions, even with older MUSL).

**Comment by eugeniykurasov** [comment]
After upgrading to 3.18 I got some issues with a DNS.
For example, I use the URL `aerserv-bc-us-east.bidswitch.net` to test truncating with DNS records.
`docker run -ti alpine:3.18 ping aerserv-bc-us-east.bidswitch.net` - returned `ping: bad address`
`docker run -ti alpine:3.17 ping aerserv-bc-us-east.bidswitch.net` - returned some IPs and then he could get a response.

**Comment by ncopa** [comment]
It resolves for me:
```console
ncopa-desktop:~$ docker run --rm -it alpine:3.18.2 ping aerserv-bc-us-east.bidswitch.net
PING aerserv-bc-us-east.bidswitch.net (35.207.61.31): 56 data bytes
64 bytes from 35.207.61.31: seq=0 ttl=56 time=110.638 ms
64 bytes from 35.207.61.31: seq=1 ttl=56 time=110.320 ms
64 bytes from 35.207.61.31: seq=2 ttl=56 time=110.289 ms
```

**Comment by eugeniykurasov** [comment]
Unfortanly `aerserv-bc-us-east.bidswitch.net` has returned just a few IPs.  We need to look at other domains with many IPs in response.

**Comment by showstopper-kz** [comment]
It's sure that nslookup and ping use different library, "1024.size.dns.netmeister.org" this domain's dns response packet size is larger than 512 byte, and nslookup will failed to resolve hostname, but ping can resolve host at alpine:3.18
<img width="1136" alt="Screenshot 2023-09-26 at 16 55 38" src="https://github.com/alpinelinux/docker-alpine/assets/60653699/0b3907f7-95f0-43e9-b0a9-bd2a1a821ddb">

**Comment by evereq** [comment]
We recently got hit by this issue with https://wasabisys.com and https://s3.wasabisys.com domains' DNS resolution (from NodeJs code).  We tried to update from `alpine3.17` to `alpine3.18` and even tried to use the `node:20.11.1-alpine3.19` docker image, but it is still the same...

In addition, tried below (installing `bind-tools`) and again no luck:

```
RUN apk --update add bash && npm i -g npm \
	&& apk add --no-cache --virtual build-dependencies bind-tools
```

**Comment by caltuntas** [comment]
> [1024.size.dns.netmeister.org](https://github.com/alpinelinux/docker-alpine/issues/326#issuecomment-1576622485)

I think, this is the main reason. My expectation was having a similar behavior with `ping` which is the part of the same binary `busybox` and resolves the first IP address successfully by using system's libc library(musl). When you check out the [source code](https://elixir.bootlin.com/busybox/latest/source/networking/ping.c) of busybox ping, it uses [xhost_and_af2sockaddr](https://elixir.bootlin.com/busybox/latest/C/ident/xhost_and_af2sockaddr) function to resolve the host. 

On the other hand, default installed busybox nslookup has two options, using libc resolver or its own resolver that still lacks `TCP fallback` for large DNS replies. By default it's configured to use its own logic on Alpine build, and configuring nslookup build option to use libc resolver would be the best option to have consistency between tools.
