### ISSUE TITLE
jq command --version flag is no longer working

### ISSUE THREAD

**Issue by luckeyca** [alpinelinux/docker-alpine#334]
with docker alpine 3.18.2, run "jq --version" returns "jq--" instead of the correct version number. with previous version(3.17.x), jq --version would return something like " jq-master-v20220328-1108-g836ca403de".

**Comment by ncopa** [comment]
We don't ship jq binary alpine docker image.
```
$ docker run --rm -it alpine:3.18.2 jq --version
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "jq": executable file not found in $PATH: unknown.
```
This should be reported somewhere else.
https://gitlab.alpinelinux.org/alpine/aports/-/issues

**Comment by ncopa** [comment]
already reported in https://gitlab.alpinelinux.org/alpine/aports/-/issues/15261
