### ISSUE TITLE
Running apk update or apk add in 3.18.x image FAILS

### ISSUE THREAD

**Issue by err0rcat** [alpinelinux/docker-alpine#337]
Cant build my own image because of this:

docker run -it alpine /bin/sh

/ # apk add --no-cache mysql-client
fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/main/x86_64/APKINDEX.tar.gz
WARNING: fetching https://dl-cdn.alpinelinux.org/alpine/v3.18/main: Permission denied
fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/community/x86_64/APKINDEX.tar.gz
WARNING: fetching https://dl-cdn.alpinelinux.org/alpine/v3.18/community: Permission denied
ERROR: unable to select packages:
  mysql-client (no such package):
    required by: world[mysql-client]
/ # 

P.S. if I'm using ubuntu images - all goes OK and my internet connection is OK.

**Comment by err0rcat** [comment]
wrong DNS configuration in underlying network

**Comment by rapekas** [comment]
Probably you are behind the proxy. You may want to add following lines into your dockerfile:
```
ENV http_proxy http://username:password@proxy_url:proxy_port
ENV https_proxy http://username:password@proxy_url:proxy_port
```
