### ISSUE TITLE
all version x86 and ram64 install ipset error

### ISSUE THREAD

**Issue by liangyuan64** [alpinelinux/docker-alpine#338]
Is there a solution to an error when s installs ipset while executing the command,only docker images.thanx

x86 docker
/etc/apk # apk add ipset
(1/2) Installing libmnl (1.0.5-r1)
(2/2) Installing ipset (7.17-r1)
Executing busybox-1.36.1-r2.trigger
OK: 8 MiB in 17 packages
/etc/apk # ipset -L
ipset v7.17: Kernel error received: Operation not permitted

arm64 docker 
~/ipset # ipset version
ipset v7.15, protocol version: 7
ipset v7.15: Cannot open session to kernel.
~/ipset # ipset list
ipset v7.15: Cannot open session to kernel.
~/ipset # ipset add

**Comment by rafitox** [comment]
i'm having the same issue! I tried to user root user, both on host and inside the container (i know it's not a good practice, but it's a testing environment). I tried to run the docker container with additional capabilities such as  NET_ADMIN, SYS_ADMIN CAP_NET_ADMIN using alpine images built with ipset. I keep getting the error message "Kernel error received: Operation not permitted". Any insights?
