### ISSUE TITLE
error with Svg\xml_parser_create()

### ISSUE THREAD

**Issue by lucabecchetti** [alpinelinux/docker-alpine#35]
I got this error on my docker:

Call to undefined function Svg\xml_parser_create()

this are my dep:

`RUN apk update \
    && apk upgrade \
    && apk add --no-cache \
		bash \
		php \
		php-xml \
        php7-gd \
		php7-zip \
		php7-pdo_mysql \
		php7-curl \
        php7-mcrypt \
		php7-mbstring \
		php7-dom \
		php7-json \
    	php7-phar \
		php7-tokenizer \
		php7-session \
		php7-fileinfo \
		php7-bcmath \
		php7-sockets \
		php7-xml \
		php7-xmlreader \
		php7-xmlwriter \
		php7-simplexml \`

From docker /bin/bash, simple file with:

$a = xml_parser_create('');

has this error:

PHP Fatal error:  Call to undefined function xml_parser_create()

Whats wrong? i have this error using dompdf! 

Thanks!

**Comment by clandmeter** [comment]
you are mixing php and php7 packages?

RUN apk update \ && apk upgrade \ && apk add --no-cache \ bash \ **php \ php-xml** \ php7-gd \ php7-zip \ php7-pdo_mysql \ php7-curl \ php7-mcrypt \ php7-mbstring \ php7-dom \ php7-json \ php7-phar \ php7-tokenizer \ php7-session \ php7-fileinfo \ php7-bcmath \ php7-sockets \ php7-xml \ php7-xmlreader \ php7-xmlwriter \ php7-simplexml \
