### ISSUE TITLE
The output from GNU Core Utilities  dd is different in apline and ubuntu

### ISSUE THREAD

**Issue by axiqia** [alpinelinux/docker-alpine#37]
Dear all,

For convenience, I test the following command all in docker.

In Ubuntu 18.04.1 LTS, the `dd` command output three lines.
```
dd if=/dev/zero of=/tmp/out bs=512 count=10
10+0 records in
10+0 records out
5120 bytes (5.1 kB, 5.0 KiB) copied, 6.6846e-05 s, 76.6 MB/s
```

While in apline 3.9.0, the `dd` command output only two lines.
``` 
dd if=/dev/zero of=/tmp/out bs=512 count=10
10+0 records in
10+0 records out
```

Any idea about it?

Thank you.

**Comment by ncopa** [comment]
This is because Alpine uses busybox `dd` by default instead of GNU `dd` from coreutils.

Run `apk add coreutils` if you want GNU `dd` instead of busybox implementation.
