### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment

### ISSUE THREAD

**Issue by AKc40** [alpinelinux/docker-alpine#388]
A fatal error has been detected by the Java Runtime Environment:
SIGSEGV (0xb) at pc=0x00007ffff7f9d9db, pid=1, tid=156
JRE version: OpenJDK Runtime Environment Corretto-21.0.2.14.1 (21.0.2+14) (build 21.0.2+14-LTS)
Java VM: OpenJDK 64-Bit Server VM Corretto-21.0.2.14.1 (21.0.2+14-LTS, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
Problematic frame:
C [ld-musl-x86_64.so.1+0x399db]
Facing same issue in jdk 17 and 21 with latter version of alpine 3.17. And unable to use 3.17 due to critical vulnerability in busybox alpine 3.17. Team Please suggest how to proceeds.
Thanks in advance.

**Comment by ncopa** [comment]
We don't ship openjdk in the alpine base image

You should ask for help from whoever provided you the openjdk binary.
