### ISSUE TITLE
Alpine container not running, status=Exited

### ISSUE THREAD

**Issue by yongkenmayo** [alpinelinux/docker-alpine#392]
Hi, I pull the alpine image to my Docker, then run the container from the alpine image. 

The container status is always "Exited". I am not sure what went wrong, will anyone of you can point out my issue? Below are the commands that I had ran.

![image](https://github.com/alpinelinux/docker-alpine/assets/169404067/8647c95e-e23c-4841-aea8-56c8f82f069f)

![image](https://github.com/alpinelinux/docker-alpine/assets/169404067/621a7a48-d3b5-400d-9c7e-ca724901d6d4)

**Comment by ns-svemu** [comment]
process completed in the container so it is exited. It's seems to be normal behaviour.

**Comment by yongkenmayo** [comment]
But to writting code into the container using VS Code, I will need the container keep running right? How to keep the container keep running if you know? Thank you.

**Comment by ncopa** [comment]
you can run it interactively with: `docker run --rm -it alpine`

There is nothing for us to fix in the docker image here so I'm closing.

Please ask for support in docker community.
