### ISSUE TITLE
aws-cli (no such package) in 3.20

### ISSUE THREAD

**Issue by gabrielcanepascalar** [alpinelinux/docker-alpine#396]
The following Dockerfile fails:

```bash
FROM alpine:3

RUN apk --update --no-cache add git aws-cli

COPY entrypoint.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
```

with

```
 > [2/3] RUN apk --update --no-cache add git aws-cli:
0.562 fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/main/x86_64/APKINDEX.tar.gz
2.834 fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/community/x86_64/APKINDEX.tar.gz
3.715 ERROR: unable to select packages:
3.715   aws-cli (no such package):
3.715     required by: world[aws-cli]
------
Dockerfile:3
--------------------
   1 |     FROM alpine:3
   2 |     
   3 | >>> RUN apk --update --no-cache add git aws-cli
   4 |     
   5 |     COPY entrypoint.sh /entrypoint.sh
--------------------
ERROR: failed to solve: process "/bin/sh -c apk --update --no-cache add git aws-cli" did not complete successfully: exit code: 1
```

It looks like `aws-cli` is missing from the 3.20 package index. Pinning to 3.19 solves the issue.

**Comment by fossdd** [comment]
aws-cli got disabled in Alpine 3.20 due to missing Python 3.12 compat. https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.20.0#aws-cli

**Comment by djsd123** [comment]
In our case we're using the bash image which is based on Alpine. Worked around this by pinning to a previous version.
```
image: bash:5.2.26-alpine3.19@sha256:890897682a8025c1e178b5ec6126b3b532ad8535f1e81dbf60bc2b7300b1bcf8
``` 

or

```
From bash:5.2.26-alpine3.19@sha256:890897682a8025c1e178b5ec6126b3b532ad8535f1e81dbf60bc2b7300b1bcf8
```

**Comment by gabrielcanepascalar** [comment]
Great ideas, @djsd123 and @fossdd. For the time being, we've pinned the image version to 3.19 while we wait for this issue to be fixed permanently.

**Comment by fossdd** [comment]
Yes, we'll add aws-cli again once upstream fixed the issue. Hopefully this is soon.

**Comment by arel** [comment]
FYI, `docker:latest` (and `docker:dind` and the other `docker:*` images I tested) updated their dependency to alpine 3.20, breaking all our automated build processes that depended on the now missing aws-cli package.

I tried several things but ended up installing aws-cli with pip as a workaround (but this is aws cli v1, so your mileage may vary).

```bash
apk add python3 py3-pip
pip3 install awscli --upgrade --break-system-packages
```

Was this not considered a breaking change?

**Comment by AntonOellerer** [comment]
`docker:26.1.2` does the deal for me

**Comment by fossdd** [comment]
> Was this not considered a breaking change?

Well, yes. Disabling packages is not very nice, but there is no other option. The best we could do is to inform people about that via the release notes.

**Comment by mahavirdarbar** [comment]
The same problem is plaguing me today; gitlab pipelines suddenly stopped working. I eventually found this [link](https://vishalvyas.com/error-unable-to-select-packages-alpine/). It now functions properly after switching to V3.9. The package should not be removed from the repository in this manner.

**Comment by fossdd** [comment]
It has to, otherwise it tries to access python packages which do not exist for it's python version. The alternative would be to package Python 3.11 on the side with all python packages, which is too much hassle for aws-cli.

If you use `:latest` or `:3` you have to know that this may break. (Usually it's fine and probably better to have the latest Alpine version, but you have to know the conseqeunces)

**Comment by berkayalan** [comment]
alpine:3.19.1 directly worked for me.

**Comment by darioackermann** [comment]
In case you're here because your pipeline broke, here are some useful pin patterns :)
* `python:alpine3.19`
* `python:3.11-alpine3.19`
* `node:lts-alpine3.19`
* `node:20-alpine3.19`
* `docker:26.1.3-alpine3.19`
* `docker:26.1.3-dind-alpine3.19`

**Comment by KorvinSzanto** [comment]
For PHP see https://hub.docker.com/_/php/tags?name=alpine3.19

**Comment by fossdd** [comment]
Good news! I have enabled and upgraded aws-cli in Alpine v3.20 by adding a bunch of patches. This is not a nice solution, but I think it's better than disabling it.

**Comment by ncopa** [comment]
We don't ship aws-cli with the alpine docker image so this should be reported and followed up on https://gitlab.alpinelinux.org/alpine/aports
