### ISSUE TITLE
Docker Alpine 3.9.3 for ARMv7 is missing on Dockerhub

### ISSUE THREAD

**Issue by frenck** [alpinelinux/docker-alpine#4]
I think something went wrong with the Docker image release of Alpine 3.9.3.
It shows up on the readme page, but the actual tag is missing.

See 3.9.3 listed in the readme on <https://hub.docker.com/r/arm32v7/alpine/>:

![image](https://user-images.githubusercontent.com/195327/55873099-0bec5780-5b8f-11e9-8182-cdaa55164ad9.png)

Missing in tags:

![image](https://user-images.githubusercontent.com/195327/55873168-36d6ab80-5b8f-11e9-8448-c9f9dd0f7216.png)

Last build:
![image](https://user-images.githubusercontent.com/195327/55873263-71404880-5b8f-11e9-9454-ce7d045e8256.png)

**Comment by frenck** [comment]
PS: This means the edge build of yesterday is missing as well.

**Comment by ncopa** [comment]
@tianon any idea what is going on here?

**Comment by frenck** [comment]
It now appeared on DockerHub. Although I feel like this closes this issue essentially, it might be worth to keep around to find out why this happened (in order to prevent it the next time).

**Comment by tianon** [comment]
Looks like a classic case of https://github.com/docker-library/official-images/issues/3835.

**Comment by frenck** [comment]
I understand, nevertheless, why update the docker hub page **before** the build has been finished?
As shown in the screenshots, according to the page shown, it should be available, while it wasn't.

**Comment by frenck** [comment]
Closing the issue, since well... it is available now. Will create a new issue if the shown page & actual images are out of sync again.
