### ISSUE TITLE
dockerhub edge being latest

### ISSUE THREAD

**Issue by nikskiz** [alpinelinux/docker-alpine#400]
Why is the `edge` release in docker hub behind `latest`?

latest:
![image](https://github.com/alpinelinux/docker-alpine/assets/16333907/d875ac79-1c1a-44ec-8461-4ebb517c6060)

edge:
![image](https://github.com/alpinelinux/docker-alpine/assets/16333907/7a3900f5-0945-41f3-b98b-160a8cd5b5b8)

**Comment by ncopa** [comment]
because we usually don't tag edge snapshots at the same time as we tag stable releases.

**Comment by nikaro** [comment]
`edge` tag has not been since a while, is it normal?
