### ISSUE TITLE
After release publication of Alpine 3.20.1 there is no official Alpine image on Docker Hub

### ISSUE THREAD

**Issue by pcoder47** [alpinelinux/docker-alpine#402]
hi, 

on 2024-06-18 Alpine project announced the release of Alpine 3.20.1
https://www.alpinelinux.org/posts/Alpine-3.20.1-released.html

When trying to use that patch already via the official Docker hub (https://hub.docker.com/_/alpine)
it turned out that the image as of today (2024-06-20) is not yet available for the tag alpine:3.20.1

Will this take a little longer?

Thanks for letting me know in this ticket.

**Comment by fossdd** [comment]
It's still being reviewed at https://github.com/docker-library/official-images/pull/17007

**Comment by james-otten-pan** [comment]
Looks like 7/8 archs got published, not seeing `amd64` yet.

**Comment by pcoder47** [comment]
Thanks for letting me know. I guess then this ticket can be closed
