### ISSUE TITLE
Timezone & time different from host

### ISSUE THREAD

**Issue by Mr-Reca** [alpinelinux/docker-alpine#44]
Hello,

I'm using an alpine image for a cronjob in a k8s cluster. In my case, my timezone is GMT/UTC +2. when I run `date` in the alpine, it shows me GMT/UTC. My host is an Ubuntu and it shows me the correct time and timezone.

How can I fix this? I also tried to add `TZ=CET date` but it still shows me GMT time. I cannot force the script to run `date -d "2 hours"` because my timezone has summer time and winter time.

Thanks,

PS: Can it be a kubernetes bug?

**Comment by Mr-Reca** [comment]
Hi again,  

Is it possible to add a feature so the container copies `/etc/localtime` into the container?

**Comment by ncopa** [comment]
You need to install the zone info database, which is not included by default:
```sh
apk add tzdata
```

Then you can set the timezone with:
```sh
export TZ=/usr/share/zoneinfo/CET
```

or:
```sh
ln -s /usr/share/zoneinfo/CET /etc/localtime
```
