### ISSUE TITLE
gdal can't load libproj, but libproj is present

### ISSUE THREAD

**Issue by senderle** [alpinelinux/docker-alpine#45]
The current version of GDAL is unable to load libproj.so. It looks (based on other tests) like some kind of ABI incompatibility.

Steps to reproduce:

    git clone https://github.com/senderle/gdaltest
    cd gdaltest
    docker build -t gdaltest .
    docker run -it gdaltest

And to verify that libproj.so is present and has the expected name (according to the error message):

    docker run -it gdaltest ls /usr/lib/libproj.so

When I tried to build postgis from source, I found that the `configure` script had similar problems; it found the correct header file but "could not find" libproj. In fact, it did find libproj, but the test failed because of what looked like an ABI incompatibility. 

I should add that I am not 100% sure I am reporting this in the right place! Let me know.

**Comment by stev-0** [comment]
This looks like it has been introduced by the most recent package 6.2.0-r0  on 10th October. I am using the previous package which installs libproj.so.15.1.1, which does not have this issue. It looks to be some sort of interaction between GDAL and proj. Probably worth raising in the proj issue tracker.

**Comment by senderle** [comment]
I built a new [working image](https://cloud.docker.com/u/senderle/repository/docker/senderle/pystgis) by compiling proj, gdal, and postgis from source. The proj and gdal versions are the most recent ones. @stev-0 not sure, but that makes it seem like this isn't an upstream issue?

**Comment by stev-0** [comment]
Main difference I can spot is you are using GDAL 3.0.1 whereas the package in the alpine repos is 2.4.0. Possibly that makes a difference but it is strange that a minor version change should cause that incompatibility

**Comment by senderle** [comment]
Yeah, worth ruling out though. If I have some time I'll test the source-compiled version with a downgraded GDAL. 

FWIW the errors I saw after digging into the configure logs suggest that it might have something to do with the packages being built with different compiler versions. Which sounds weird, but I can't make better sense of any other idea.

**Comment by xxRockOnxx** [comment]
Thanks @senderle! The only changes I did on my Dockerfile that I copied from yours to make it work again are:

- remove `proj` from `apk add`
- download the 6.2.0 proj tar like in your [Dockerfile](https://hub.docker.com/r/senderle/pystgis/dockerfile)
- extract proj
- install `sqlite` and `sqlite-dev`
- compile Proj
- compile postgis

```
FROM postgres:11-alpine
MAINTAINER Lemuel Flores <is101.lemuel@gmail.com>

ENV PROJ_VERSION 6.2.0
ENV PROJ_MD5 5cde556545828beaffbe50b1bb038480
ENV POSTGIS_VERSION 3.0.0
ENV POSTGIS_SHA256 1c83fb2fc8870d36ed49859c49a12c8c4c8ae8c5c3f912a21a951c5bcc249123

RUN set -ex \
    \
    && apk add --no-cache --virtual .fetch-deps \
        ca-certificates \
        openssl \
        tar \
    \
    && wget -O proj.tar.gz "https://download.osgeo.org/proj/proj-$PROJ_VERSION.tar.gz" \
    && echo "$PROJ_MD5 *proj.tar.gz" | md5sum -c - \
    && mkdir -p /usr/src/proj \
    && tar \
        --extract \
        --file proj.tar.gz \
        --directory /usr/src/proj \
        --strip-components 1 \
    && rm proj.tar.gz \
    \
    && wget -O postgis.tar.gz "https://github.com/postgis/postgis/archive/$POSTGIS_VERSION.tar.gz" \
    && echo "$POSTGIS_SHA256 *postgis.tar.gz" | sha256sum -c - \
    && mkdir -p /usr/src/postgis \
    && tar \
        --extract \
        --file postgis.tar.gz \
        --directory /usr/src/postgis \
        --strip-components 1 \
    && rm postgis.tar.gz \
    \
    && apk add --no-cache --virtual .build-deps \
        autoconf \
        automake \
        g++ \
        json-c-dev \
        libtool \
        libxml2-dev \
        make \
        perl \
    \
    && apk add --no-cache --virtual .build-deps-testing \
        --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing \
        gdal-dev \
        geos-dev \
        sqlite-dev \
        sqlite \
        protobuf-c-dev \
    && cd /usr/src/proj \
    && ./configure \
    && make \
    && make install \
    && cd / \
    \
    && cd /usr/src/postgis \
    && ./autogen.sh \
# configure options taken from:
# https://anonscm.debian.org/cgit/pkg-grass/postgis.git/tree/debian/rules?h=jessie
    && ./configure \
#       --with-gui \
    && make \
    && make install \
    && apk add --no-cache --virtual .postgis-rundeps \
        json-c \
    && apk add --no-cache --virtual .postgis-rundeps-testing \
        --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing \
        geos \
        gdal \
        proj \
        protobuf-c \
    && cd / \
    && rm -rf /usr/src/postgis \
    && apk del .fetch-deps .build-deps .build-deps-testing
```

**Comment by cigzigwon** [comment]
Before calling ./configure on postgis you need...
`&& touch build-aux/config.rpath \`
to circumvent an issue w/autoconf

**Comment by ncopa** [comment]
I'm not sure what we can do in the alpine image about this.

There is also a postgis package nowadays. `apk add postgis`
