### ISSUE TITLE
update to node v13.0.1

### ISSUE THREAD

**Issue by fatlinesofcode** [alpinelinux/docker-alpine#47]
there is a bug with npm in node v13
```
npm WARN npm npm does not support Node.js v13.0.0
```
its fixed in latest release

ref, https://github.com/nodejs/node/issues/30066

**Comment by damianobarbati** [comment]
Hey @ncopa, node v12 is currently the LTS. 
Do you have any idea when will be the repository be updated?

Because, currently we have: nodejs => 10 and nodejs-current => 12
It should be: nodejs => 12 and nodejs-current => 13

Thanks!

**Comment by damianobarbati** [comment]
@fatlinesofcode can this be closed? node v12 has landed on alpine as "nodejs" and v13 as "nodejs-current"

**Comment by liqiankl** [comment]
I had a similar issue this worked for me "yarn install --ignore-engines"
