### ISSUE TITLE
arm64v8/alpine:3.10 - qemu: Unsupported syscall: 283

### ISSUE THREAD

**Issue by sooslaca** [alpinelinux/docker-alpine#48]
hi,

Something change in 3.10 image, same is working fine in 3.9.
I continuously get `qemu: Unsupported syscall: 283`

**Steps to reproduce:**
I'm using Ubuntu 18.04.3 LTS.
`Linux testubuntu 4.15.0-66-generic #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

Docker version
```
Client: Docker Engine - Community
 Version:           19.03.4
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        9013bf583a
 Built:             Fri Oct 18 15:54:09 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.4
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       9013bf583a
  Built:            Fri Oct 18 15:52:40 2019
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

Commands to run as an example:
```
root@testubuntu:~# apt-get install -y qemu-user-static

root@testubuntu:~# docker run -it --rm -v /usr/bin/qemu-aarch64-static:/usr/bin/qemu-aarch64-static arm64v8/alpine:3.10 /bin/sh
/ # apk add git
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/aarch64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/community/aarch64/APKINDEX.tar.gz
(1/6) Installing ca-certificates (20190108-r0)
(2/6) Installing nghttp2-libs (1.39.2-r0)
(3/6) Installing libcurl (7.66.0-r0)
(4/6) Installing expat (2.2.8-r0)
(5/6) Installing pcre2 (10.33-r0)
(6/6) Installing git (2.22.0-r0)
Executing busybox-1.30.1-r2.trigger
Executing ca-certificates-20190108-r0.trigger
OK: 21 MiB in 20 packages
/ # git clone https://github.com/thockin/test /test
Cloning into '/test'...
qemu: Unsupported syscall: 283   <<<<<< THIS
qemu: Unsupported syscall: 283   <<<<<< IS NOT HERE IN ALPINE 3.9
remote: Enumerating objects: 56, done.
remote: Total 56 (delta 0), reused 0 (delta 0), pack-reused 56
Unpacking objects: 100% (56/56), done.
```

Same commands run with alpine:3.9
```
root@testubuntu:~# docker run -it --rm -v /usr/bin/qemu-aarch64-static:/usr/bin/qemu-aarch64-static arm64v8/alpine:3.9 /bin/sh
/ # apk add git
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/main/aarch64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.9/community/aarch64/APKINDEX.tar.gz
(1/7) Installing ca-certificates (20190108-r0)
(2/7) Installing nghttp2-libs (1.35.1-r1)
(3/7) Installing libssh2 (1.9.0-r1)
(4/7) Installing libcurl (7.64.0-r3)
(5/7) Installing expat (2.2.8-r0)
(6/7) Installing pcre2 (10.32-r1)
(7/7) Installing git (2.20.1-r0)
Executing busybox-1.29.3-r10.trigger
Executing ca-certificates-20190108-r0.trigger
OK: 20 MiB in 21 packages
/ # git clone https://github.com/thockin/test /test
Cloning into '/test'...
remote: Enumerating objects: 56, done.
remote: Total 56 (delta 0), reused 0 (delta 0), pack-reused 56
Unpacking objects: 100% (56/56), done.
```

Anyone has an idea how to debug this further?

Thanks

**Comment by dmizelle** [comment]
Passing by -- I'm not sure how spawning `/bin/sh` even works. How would you even run an arm64v8 image on an amd64 host?

```
Server:
 Engine:
  Version:          19.03.4-ce
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.1
  Git commit:       9013bf583a
  Built:            Sat Oct 19 04:39:38 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.0.m
  GitCommit:        d50db0a42053864a270f648048f9a8b4f24eced3.m
 runc:
  Version:          1.0.0-rc9
  GitCommit:        d736ef14f0288d6993a1845745d6756cfc9ddd5a
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

```
Linux hermes 5.3.8-arch1-1 #1 SMP PREEMPT @1572357769 x86_64 GNU/Linux
```

```
Unable to find image 'arm64v8/alpine:3.10' locally
3.10: Pulling from arm64v8/alpine
8bfa91304040: Pull complete
Digest: sha256:1827be57ca85c28287d18349bbfdb3870419692656cb67c4cd0f5042f0f63aec
Status: Downloaded newer image for arm64v8/alpine:3.10
standard_init_linux.go:211: exec user process caused "exec format error"
```

Anyways, besides whatever wizardry is going on here:

syscall 283 on arm64 is `membarrier`. looking at `membarrier(2)`, it looks like a lot of membarrier-related things changed around kernel 4.16.

http://man7.org/linux/man-pages/man2/membarrier.2.html

Can you try upgrading your kernel?

**Comment by sooslaca** [comment]
looks like 4.15 is the latest on ubuntu 18.04 LTS now. Also I'm not sure: if it was kernel problem why alpine 3.9 works while 3.10 fails.

What if you run the same command as I did above? with alpine 3.10 you get the qemu error?

This package needed to be installed `qemu-user-static` under Ubuntu at least.

Thanks

**Comment by dmizelle** [comment]
Hm, I'm not seeing this issue:

```
[devon@hermes tmp]$ docker run --rm -it arm64v8/alpine:3.10 /bin/sh
/ # apk add git
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/aarch64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/community/aarch64/APKINDEX.tar.gz
(1/6) Installing ca-certificates (20190108-r0)
(2/6) Installing nghttp2-libs (1.39.2-r0)
(3/6) Installing libcurl (7.66.0-r0)
(4/6) Installing expat (2.2.8-r0)
(5/6) Installing pcre2 (10.33-r0)
(6/6) Installing git (2.22.0-r0)
Executing busybox-1.30.1-r2.trigger
Executing ca-certificates-20190108-r0.trigger
OK: 21 MiB in 20 packages
# git clone https://github.com/thockin/test /test
Cloning into '/test'...
remote: Enumerating objects: 56, done.
remote: Total 56 (delta 0), reused 0 (delta 0), pack-reused 56
Unpacking objects: 100% (56/56), done.
```

However, I got to thinking more about this.

The error is actually coming from `qemu`, not your Kernel, so I did some digging. What version of `qemu` do you have?

```
[devon@hermes tmp]$ qemu-aarch64-static -version
qemu-aarch64 version 4.1.0
Copyright (c) 2003-2019 Fabrice Bellard and the QEMU Project developers
```

Looks like the version of qemu on 18.04 is 2.11: https://packages.ubuntu.com/bionic/qemu-user-static

Judging by the commit history of qemu, `membarrier` wasn't enabled until 2.12.
https://github.com/qemu/qemu/commit/a40161cbe9ccbcbab798c3e4d257c4bba99d153a

You may _also_ still need to upgrade the kernel as well, but what if you were to upgrade the version of qemu you are using? 

Also, it may honestly be safe to just ignore these warnings. It doesn't look like they are fatal.

**Comment by sooslaca** [comment]
hi @dmizelle ,

Thanks for the replies.
```
root@testubuntu:/home/laca# apt update
All packages are up to date.
root@testubuntu:/home/laca# qemu-aarch64-static -version
qemu-aarch64 version 2.11.1(Debian 1:2.11+dfsg-1ubuntu7.19)
```

Why does `membarrier` required for alpine 3.10 but not for alpine3.9? Do you have an idea?

As much as I remember if I compile packages with the error being there it's not running on real aarch64 platform, that was my problem. But I can retest indeed. Thanks

**Comment by dmizelle** [comment]
Taking a stab in the dark at this, but musl (the libc used by Alpine) only added `membarrier` support recently. http://git.musl-libc.org/cgit/musl/commit/?id=ba18c1ecc6a18203ad8496791154af86f706f632

Whether the date of the change lines up with the version bump from Alpine 3.9 to 3.10, I'm not sure.

**Comment by sooslaca** [comment]
Thanks, that's a good stab ;)
[https://en.wikipedia.org/wiki/Alpine_Linux](https://en.wikipedia.org/wiki/Alpine_Linux) says 3.9 was released 29th Jan 2019.

The commit you linked is from 22nd Febr 2019, so I would assume the commit is not in 3.9 and that's why it does not give the error.

Let me close this thread and let's wait for an updated qemu/kernel version on ubuntu.

Thanks for the hints @dmizelle
