### ISSUE TITLE
wget command issue

### ISSUE THREAD

**Issue by Hokwang** [alpinelinux/docker-alpine#51]
I tested from alpine:3.2 to alpine:3.10 and also edge.

the problem is wget command does not work propery.
```
# docker run --rm -it alpine:edge
Unable to find image 'alpine:edge' locally
edge: Pulling from library/alpine
ae4a0e1e8235: Pull complete 
Digest: sha256:77c2c4d3d94753cacc93fbee059ef20b6df1386f98f259e41632ab39d13a0f6a
Status: Downloaded newer image for alpine:edge
/ # export http_proxy=http://proxy:port
/ # export https_proxy=http://proxy:port
/ # wget "https://binaries.sonarsource.com/Distribution/sonar-java-plugin/sonar-java-plugin-5.14.0.18788
.jar" --no-check-certificate
Connecting to proxy:port (proxy:port)
wget: server returned error: HTTP/1.1 400 Bad Request
```

Find out solution is re-install wget and openssl.
```
# docker run --rm -it alpine:edge
/ # export HTTP_PROXY=http://proxy:port
/ # export HTTPS_PROXY=http://proxy:port
/ # apk --no-cache add openssl wget
fetch http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
(1/2) Installing openssl (1.1.1d-r2)
(2/2) Installing wget (1.20.3-r0)
Executing busybox-1.31.0-r1.trigger
OK: 7 MiB in 16 packages
/ # export http_proxy=http://proxy:port
/ # export https_proxy=http://proxy:port
/ # wget "https://binaries.sonarsource.com/Distribution/sonar-java-plugin/sonar-java-plugin-5.14.0.18788
.jar" --no-check-certificate
--2019-11-14 02:59:42--  https://binaries.sonarsource.com/Distribution/sonar-java-plugin/sonar-java-plugin-5.14.0.18788.jar
Connecting to proxy:port... connected.
Proxy request sent, awaiting response... 200 OK
Length: 8348625 (8.0M) [application/x-java-archive]
Saving to: 'sonar-java-plugin-5.14.0.18788.jar'

.jar                       30%[==========>                           ]   2.46M   209KB/s    eta 29s
```

I refered Yelp/dumb-init#73

**Comment by Seb35** [comment]
I was suprised my command wget with advanced options did not work, but with further research this is the intended behaviour:

The `wget` out-of-the-box is provided by BusyBox:
```
/ # wget --help
BusyBox v1.31.1 () multi-call binary.

Usage: wget [-c|--continue] [--spider] [-q|--quiet] [-O|--output-document FILE]
	[-o|--output-file FILE] [--header 'header: value'] [-Y|--proxy on/off]
	[-P DIR] [-S|--server-response] [-U|--user-agent AGENT] [-T SEC] URL...
... 13 lines of options
```
And when the package `wget` is installed, we obtain:
```
/ # wget --help
GNU Wget 1.20.3, a non-interactive network retriever.
Usage: wget [OPTION]... [URL]...
... 201 lines of options
```

**Comment by aoot** [comment]
> I was suprised my command wget with advanced options did not work, but with further research this is _probably_ the intended behaviour:
> 
> The `wget` out-of-the-box is provided by BusyBox:
> 
> ```
> / # wget --help
> BusyBox v1.31.1 () multi-call binary.
> 
> Usage: wget [-c|--continue] [--spider] [-q|--quiet] [-O|--output-document FILE]
> 	[-o|--output-file FILE] [--header 'header: value'] [-Y|--proxy on/off]
> 	[-P DIR] [-S|--server-response] [-U|--user-agent AGENT] [-T SEC] URL...
> ... 13 lines of options
> ```
> 
> And when the package `wget` is installed, we obtain:
> 
> ```
> / # wget --help
> GNU Wget 1.20.3, a non-interactive network retriever.
> Usage: wget [OPTION]... [URL]...
> ... 201 lines of options
> ```

@Seb35 recommendation helped me.

It seems that I have to install `wget` with a separate line instead of part of a list of packages that I'm trying to install with `apk --no-cache add wget` as for some reason it doesn't get installed properly if `wget` is part of a list of packages. 

Thanks,
