### ISSUE TITLE
Upgrade to node12 LTS

### ISSUE THREAD

**Issue by emilioSp** [alpinelinux/docker-alpine#54]
Hi @ncopa,

I use alpine and node in production. I want to upgrade to node 12 LTS.

Do you know when it will be an upgrade of the alpine version with node 12 LTS?

Thanks!

**Comment by daveisfera** [comment]
Using the `node` docker image with alpine as the base should be the easiest way to do that:
https://hub.docker.com/_/node

**Comment by ncopa** [comment]
nodejs 12 was introduced with alpinelinux/aports@83248509e435971957582bb985fac43e791abad5 and is currently availabe in `alpine:edge`. It will be available in `alpine:3.11` which will be released within a few weeks hopefully.
