### ISSUE TITLE
File /etc/shadow group is not root

### ISSUE THREAD

**Issue by nguse** [alpinelinux/docker-alpine#6]
Of the entire filesystem, only /etc/shadow is not owned by root:root, it is owned by root:shadow. Is this intentional?

alpine:3.9

```
find / ! -user root

find / ! -group root
/etc/shadow

ls -l /etc/shadow
-rw-r-----    1 root     shadow         441 Apr  8 20:30 /etc/shadow
```

**Comment by mattlorimor** [comment]
Yes, this is intentional. It is done this way to make the `/etc/passwd` and `/etc/shadow` files work together properly.

> Systems administrators can reduce the likelihood of brute-force attacks by making the list of hashed passwords unreadable by unprivileged users. The obvious way to do this is to make the passwd database itself readable only by the root user. However, this would restrict access to other data in the file such as username-to-userid mappings, which would break many existing utilities and provisions. One solution is a "shadow" password file to hold the password hashes separate from the other data in the world-readable passwd file. For local files, this is usually /etc/shadow on Linux and Unix systems, or /etc/master.passwd on BSD systems; each is readable only by root. (Root access to the data is considered acceptable since on systems with the traditional "all-powerful root" security model, the root user would be able to obtain the information in other ways in any case). Virtually all recent Unix-like operating systems use shadowed passwords.

https://en.wikipedia.org/wiki/Passwd#Shadow_file

**Comment by thanatos** [comment]
The quoted passage explains why `shadow` exists as a separate file. It does not answer the original poster's question of why the group is `shadow`. A file `root:root` and `600` (`rw-------  root:root`) would also be unreadable by anyone except root, and much more clearly so. (And this is how, e.g., Gentoo Linux does it.)

**Comment by ncopa** [comment]
> Of the entire filesystem, only /etc/shadow is not owned by root:root, it is owned by root:shadow. Is this intentional?

Yes. See commit [b973cd7a0](https://git.alpinelinux.org/aports/commit/?id=b973cd7a0) and issue [#3349](https://bugs.alpinelinux.org/issues/3349)

Basically, it allows users in group `shadow` to verify passwords without needing suid root.
