### ISSUE TITLE
JDK 11.0.5 crashed in apline-glibc

### ISSUE THREAD

**Issue by menghuxiashan** [alpinelinux/docker-alpine#62]
Dockerfile:
FROM frolvlad/alpine-glibc:latest
RUN mkdir -p /usr/java/
ADD jdk-11.0.5_linux-x64_bin.tar.gz /usr/java/
ENV JAVA_HOME=/usr/java/jdk-11.0.5
ENV PATH ${PATH}:${JAVA_HOME}/bin

when enter container and input command:
/ # java -version
java version "11.0.5" 2019-10-15 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.5+10-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.5+10-LTS, mixed mode)
[thread 11 also had an error]

A fatal error has been detected by the Java Runtime Environment:
SIGSEGV (0xb) at pc=0x00007f28dcb2aab1, pid=6, tid=21
JRE version: Java(TM) SE Runtime Environment (11.0.5+10) (build 11.0.5+10-LTS)
Java VM: Java HotSpot(TM) 64-Bit Server VM (11.0.5+10-LTS, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
Problematic frame:
C [libc.so.6+0x11dab1][thread 12 also had an error]
Core dump will be written. Default location: Core dumps may be processed with "/usr/libexec/abrt-hook-ccpp %s %c %p %u %g %t e %P %I %h" (or dumping to //core.6)
An error report file with more information is saved as:
//hs_err_pid6.log
[thread 9 also had an error]
[thread 16 also had an error]
[thread 13 also had an error]
[thread 7 also had an error]

If you would like to submit a bug report, please visit:
http://bugreport.java.com/bugreport/crash.jsp
Aborted (core dumped)

**Comment by ncopa** [comment]
We don't support glibc.
