### ISSUE TITLE
Not able to use Alpine OS on EC2 instance

### ISSUE THREAD

**Issue by akanshgulati** [alpinelinux/docker-alpine#63]
Tried to SSH on Alpine OS installed using Alpine OS on Marketplace. 
https://aws.amazon.com/marketplace/pp/B07Q4Q8KV5#pdp-support
`ssh -i <pemfile> root@IP`
It's requesting for root password and not able to find the default password in this case, please help.

**Comment by oxr463** [comment]
That image is provided by [okindev](https://aws.amazon.com/marketplace/seller-profile?id=cb7c530c-e0a9-416f-8252-4e25b58ca513&ref=dtl_B07Q4Q8KV5), you should reach out to them instead.

**Comment by akanshgulati** [comment]
Thanks. Will reach out to them.
