### ISSUE TITLE
chpasswd is not working correctly.

### ISSUE THREAD

**Issue by wgillaspy** [alpinelinux/docker-alpine#7]
echo "avaliduser:apassword" | chpasswd

results in: 

#Password:
#chpasswd: PAM: Authentication failure

Same issue reported here: https://stackoverflow.com/questions/55475157/pam-authentication-failure-when-running-chpasswd-on-alpine-linux

Using a previous alpine version corrects the issue.

**Comment by FlorentLMI** [comment]
Probably related to https://github.com/alpinelinux/aports/commit/72c7a7a3caf28c06289dc5f65e1756b38cfb00ca

**Comment by ncopa** [comment]
Is this still an issue? I'm not able to reproduce:
````
ncopa-desktop:~$ docker run --rm -it alpine:3.10
/ # echo "root:yadda" | chpasswd
chpasswd: password for 'root' changed
````

**Comment by wgillaspy** [comment]
Looks like its fixed.
