### ISSUE TITLE
INSTALL: applet not found

### ISSUE THREAD

**Issue by Fazendaaa** [alpinelinux/docker-alpine#70]
I'm messing with the new buildx feature that Docker released to write a tutorial on how to build an R  application for multi-platform platforms. On the amd64 and arm64 architectures I am not having any problems, but I got stuck on arm32v7 when running the following command:

```shell
 R -e "install.packages ('Rcpp', repos = 'https: //brieger.esalq.usp.br/CRAN/')"

The R gives me the following error:

trying URL 'https://brieger.esalq.usp.br/CRAN/src/contrib/Rcpp_1.0.3.tar.gz'
Content type 'application / x-gzip' length 2749025 bytes (2.6 MB)
==================================================
downloaded 2.6 MB

INSTALL: applet not found

The downloaded source packages are in
‘/ Tmp / RtmppbkEhI / downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning messages:
1: In system2 (cmd0, args, env = env, stdout = outfile, stderr = outfile,:
  error in running command
2: In install.packages ("Rcpp", repos = "https://brieger.esalq.usp.br/CRAN/"):
  installation of package ‘Rcpp’ had non-zero exit status
```

I know this could be a problem with this package itself, however, by commenting on this line in my Dockerfile and going to the next one:

```shell
git clone https://github.com/r-lib/fs && R CMD INSTALL fs && rm -rf fs
```

The same mistake `INSTALL: applet not found` happens:

```shell
Cloning into 'fs'...
remote: Enumerating objects: 273, done.
remote: Counting objects: 100% (273/273), done.
remote: Compressing objects: 100% (161/161), done.
remote: Total 31101 (delta 198), reused 145 (delta 104), pack-reused 30828
Receiving objects: 100% (31101/31101), 7.52 MiB | 4.95 MiB/s, done.
Resolving deltas: 100% (24491/24491), done.
INSTALL: applet not found
```

My question is whether this is a problem with the image itself or something else? And I wonder  this because [R has support for armv7](https://pkgs.alpinelinux.org/package/edge/community/armv7/R).

I thank and feel sorry for the inconvenience, I tried to look at Stackoverflow before opening this issue.

**Comment by Fazendaaa** [comment]
After I removed `linux/arm/v7` from `--platform`, the `linux/arm64` started to present the same error. Could this possible be an buildx error?

**Comment by kevinelliott** [comment]
@Fazendaaa I experience the same exact issue. How have you resolved this?

**Comment by Fazendaaa** [comment]
@kevinelliott, I opened an [issue](https://gitlab.alpinelinux.org/alpine/infra/infra-packages/issues/1#note_71762) in GitLab, if you need any help, please tell me that I try to share the build script that I created with you.
