### ISSUE TITLE
Newer release of alpine 3.11.4  with kernel to 5.3.15+, 5.4.2+, or 5.5+ - to support golang 1.14 ? 

### ISSUE THREAD

**Issue by akkumar** [alpinelinux/docker-alpine#71]
With golang 1.14 released recently, it "discovered" a bug in Linux kernel . 

```
runtime: mlock of signal stack failed: 12
runtime: increase the mlock limit (ulimit -l) or
runtime: update your kernel to 5.3.15+, 5.4.2+, or 5.5+
fatal error: mlock failed
```

[ More background in [golang issue#37436](https://github.com/golang/go/issues/37436
) ]

Currently , alpine 3.11.3 has this. 

```
/ # uname -r
5.3.0-40-generic
```

It would be nice to have some kind of an emergency release, say 3.11.4 with the mentioned kernel in them. 

Or , say an approximate timeline when we can expect one.  Much appreciate the help.

**Comment by clandmeter** [comment]
You are not running an Alpine Linux kernel. `5.3.0-40-generic` points to an ubuntu kernel.
Please check the hosts operating system and update it if possible, else contact that specific distro with your bug report.

**Comment by akkumar** [comment]
Oops. Bad call ! Closing it as not applicable.
