### ISSUE TITLE
[Google Cloud Run] Unsupported syscall membarrier

### ISSUE THREAD

**Issue by ynwd** [alpinelinux/docker-alpine#75]
Image: 
node:alpine

Container Sandbox: Unsupported syscall membarrier(0x10,0x0,0x0,0x8,0x0,0x0). It is very likely that you can safely ignore this message and that this is not the cause of any error you might be troubleshooting. Please, refer to https://gvisor.dev/c/linux/amd64/membarrier for more information.

Link: https://github.com/google/gvisor/issues/267#issuecomment-562204277

**Comment by ncopa** [comment]
I dont think this is a problem or bug in alpine base image. It sounds like there is a sandbox that filters membarrier syscall. The proper fix for this is to allow or whitelist the membarrier syscall (which is used by musl libc). We need to patch both [firefox](https://git.alpinelinux.org/aports/tree/community/firefox-esr/fix-sandbox-membarrier.patch) and [chromium](https://git.alpinelinux.org/aports/tree/community/chromium/musl-sandbox.patch) for that.

Other possibility is that the host kernel is old enough to not support this syscall (older than linux 4.3)

In either case, I don't think this is anything we can fix in the alpine base image. Feel free to reopen if you have a suggestion on how we can fix it in the base image.
