### ISSUE TITLE
Docker Hub Tag for 3.11.6 didn't build amd64 or 386 versions

### ISSUE THREAD

**Issue by cwimmer** [alpinelinux/docker-alpine#80]
<img width="1269" alt="Screen Shot 2020-04-23 at 11 18 09 AM" src="https://user-images.githubusercontent.com/630964/80134957-5ea77000-8554-11ea-82c7-66b10eb40e72.png">
All the tags that were built today include the correct architectures except for the 3.11.6 tag.  It only has armv6.

**Comment by jumanjiman** [comment]
amd64 is now available on docker hub.

**Comment by ncopa** [comment]
They are there now.

```
$ docker pull alpine:3.11.6
3.11.6: Pulling from library/alpine
cbdbe7a5bc2a: Pull complete 
Digest: sha256:9a839e63dad54c3a6d1834e29692c8492d93f90c59c978c1ed79109ea4fb9a54
Status: Downloaded newer image for alpine:3.11.6
docker.io/library/alpine:3.11.6
```
