### ISSUE TITLE
Salt-Master Vulnerability

### ISSUE THREAD

**Issue by M30HRG** [alpinelinux/docker-alpine#81]
Hey all, 

I'm currently running Alpine:3.11.6 which gives me salt-master 3000.1-rc2 - As we are aware of a new CVE vuln, scored at 10- We need to get the latest version of salt-master into Alpine. 

Ref: https://github.com/saltstack/community/blob/master/doc/Community-Message.pdf

Is this something that can be done/being worked on by Alpine/something I can undertake?

Many thanks,

**Comment by clandmeter** [comment]
salt has been upgraded on both 3.11 and edge

**Comment by M30HRG** [comment]
Unfortunately, 3.11 doesn’t include version 2019.2.4 which fixes the vulnerability CVE. Edge is also the same. This fix was released 2 days ago.

Hopefully this can be included 🙂

**Comment by clandmeter** [comment]
Please check:
https://github.com/alpinelinux/aports/commit/b244804c35a8cc17470ee3e995fb651682ab0063
https://github.com/alpinelinux/aports/commit/4d854e9279196468105190938da4c654baf2fcac

**Comment by M30HRG** [comment]
That’s amazing. 

Thank you 🙂
