### ISSUE TITLE
openssh-client: ssh emits pubkey error

### ISSUE THREAD

**Issue by gtowey** [alpinelinux/docker-alpine#89]
```
ssh -i ssh-key user@host.example.com hostname
load pubkey "ssh-key": invalid format
host.example.com
```

The ssh command emits that error messges *and still successfully connects*. 

They key has not changed and works just fine with the version of `openssh-client` in Alpine `3.11`.  This breaks in `3.12`.

**Comment by gillesdouaire** [comment]
same here. I am puzzled. Just worried that at some point, it will stop working.

**Comment by gillesdouaire** [comment]
@gtowey it's related to the openssh version. you need to switch your key from (likely) rsa to ed25519. For me it worked.

**Comment by kissgyorgy** [comment]
> you need to switch your key from (likely) rsa to ed25519.

I'm on 3.13, using ed25519 keys and I have the same error message 😢

**Comment by kissgyorgy** [comment]
It was because there were no newline at the end of the file.

**Comment by Christopher-Hayes** [comment]
> It was because there were no newline at the end of the key file.

My god.

**Comment by gtowey** [comment]
yeah this solution worked for me; closing issue because of pebkac
